Added Apache v2 LICENSE
malex984/dockapp pull request #45
Opened 2016-11-13 14:08 UTC by malex984

1. Added LICENSE
2. Added NOTICE
3. Added references to README.md

2016-11-13 14:09 UTC, malex984 commented
Please check the added NOTICE file.

2016-11-14 08:23 UTC, porst17 requested changes
The official name of the company is `IMAGINARY gGmbH`, not `IMAGINARY - open mathematics`.

2016-11-14 08:23 UTC, porst17 commented on NOTICE
> +   Copyright 2016 IMAGINARY – open mathematics
`IMAGINARY - open mathematics` -> `IMAGINARY gGmbH`

2016-11-14 08:23 UTC, porst17 commented on LICENSE
> +   Copyright 2016 IMAGINARY – open mathematics
`IMAGINARY - open mathematics` -> `IMAGINARY gGmbH`

2016-11-14 10:36 UTC, malex984 commented on LICENSE
> +   Copyright 2016 IMAGINARY – open mathematics
fixed

2016-11-14 10:44 UTC, porst17 approved these changes

2016-11-14 12:06 UTC, merged